config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  resources :users do
    resources :posts
  end
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attr_accessor :image
  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # validates :name, presence: true, length: { maximum: 30 }
  # validates :username, presence: true, length: { maximum: 10 },
  #                      uniqueness: true
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, length: { maximum: 100 },
  #                   format: { with: VALID_EMAIL_REGEX },
  #                   uniqueness: { case_sensitive: false }
  # validates :password, presence: true, length: { minimum: 8, maximum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(post_params)
    redirect_to user_posts_path
  end

  def index
    @user = User.find(params[:user_id])
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:message, :user_id, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = user_from_params
    @user.save
    if @user.save
      redirect_to @user
    else
      render '/'
    end
  end

  private
  def user_from_params
    user_params = params[:user] || Hash.new
    name = user_params.delete(:name)
    username = user_params.delete(:username)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.name = name
      user.username = username
      user.email = email
      user.password = password
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper # :nodoc:
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h2>Posts</h2>
<% @posts.order('created_at DESC').each do |post| %>
  <p>
    <%= post.message %>
    <%= image_tag post.image_url.to_s %>
  </p>
<% end %>

<%= link_to 'New Post', new_user_post_path(@user) %>

app/views/posts/new.html.erb
<h2>New Post:</h2>
<%= form_for :post, html: {multipart: true}, url: user_posts_path(params[:user_id]) do |form| %>
  <%= form.text_area :message %><br>
  <%= form.file_field :image %><br>
  <%= form.submit "Post" %>
<% end %>

app/views/users/new.html.erb
<h1>Welcome to Instagram!</h1>
<h1>Sign Up</h1>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit 'Sign up' %>
  </p>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

<%= link_to 'New Post', new_user_post_path(@user) %>